### ISSUE TITLE
error:missing script:docs

### ISSUE THREAD

**Issue by sccdcwc** [Kocal/jsdoc-vuejs#10]
$ npm install && npm run docs
when I run this command,it shows 'missing script:docs'. what's wrong?How to solve it? Thanks.

**Comment by sccdcwc** [comment]
I got it what wrong is.I should write the package.json to let it know what docs is! Thanks!

**Comment by Kocal** [comment]
The command `npm run docs` should be run inside folder `example`.

Maybe it's not very clear in the README ... 🤔
