### ISSUE TITLE
SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by Radiergummi** [Kocal/jsdoc-vuejs#12]
I'm sorry, it's me again 😅   I'm currently working on an ES6-only Vue project and stumbled across the following error:  

```
export default {
^^^^^^

SyntaxError: Unexpected token export
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:588:28)
    at loader (node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at evalmachine.<anonymous>:11:18
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at module.exports (node_modules/jsdoc-vuejs/lib/vueComponentPrototypeExtractor.js:22:10)
    at exports.Parser.beforeParse (node_modules/jsdoc-vuejs/index.js:20:47)
    at emitOne (events.js:115:13)
    at exports.Parser.emit (events.js:210:7)
    at exports.Parser.Parser._parseSourceCode (node_modules/jsdoc/lib/jsdoc/src/parser.js:248:14)
```

Seems to come from here: 

```js
/**
 * Extract prototype from a Vue Component, after a passage of Babel.
 * @param {Object} transformedSource
 * @param {String} fullFilename
 */
module.exports = function (transformedSource, fullFilename) {
  const sandbox = createSandbox(fullFilename)
  const context = vm.createContext(sandbox)
  const script = new vm.Script(`
    // transform ES6 import/exports to require/module.exports (NodeJS compatible)
    require('babel-register');
    
    ${transformedSource.code}`
  )

  script.runInContext(context)

  return context.exports.default // Vue component prototype
}
```

I have several components ending in `.vue` and one `.js` mixin most of them `import`. This error seems to happen once I import the mixin somewhere...

**Comment by Kocal** [comment]
That's probably because `babel-register` is not installed.

I didn't put it in `package.json`'s project because I relied on the fact that `babel-register` is already installed with webpack Vue template.

**Comment by Radiergummi** [comment]
Okay, think I've got it now. `babel-register` is indeed installed, but it seems like if you `import` from .js files instead of .vue files, it breaks. I just moved all mixin code into a .vue file containing only the script tag and now the error is gone.

**Comment by Kocal** [comment]
Well, that's because of [this](https://github.com/Kocal/jsdoc-vuejs/blob/master/lib/requireHookForVue.js)

As you can see, only `.vue` is passed onto Babel, not `.js`.
And... since ES6 `import`/`export` are not already supported by Node, it fails

**Comment by Radiergummi** [comment]
Ha, okay, that makes sense actually. Considering the inspected script is running in a sandbox, would it hurt to extend the hook to `.js` files?

**Comment by Kocal** [comment]
Mmmh, since it's only for documentation, I think not...
Maybe you can do a PR :D

**Comment by Radiergummi** [comment]
I've already played around a bit, results in the original error, though D:  
I'll have a look the next days!

**Comment by Kocal** [comment]
Even with something like that? :(

```js
require.extensions['.js'] = function (module, filename) {
  const source = fs.readFileSync(filename, 'utf8')
  const transformedSource = transformSource(source)

  return module._compile(transformedSource.code, filename)
}```

**Comment by Radiergummi** [comment]
Yup, that was my first try...

**Comment by Kocal** [comment]
Erf... :(

**Comment by ccqgithub** [comment]
@Kocal this can solve the issue
```
const script = new vm.Script(`
    // transform ES6 import/exports to require/module.exports (NodeJS compatible)
    require('babel-register')({
      "presets": [
        ["env", {
          "targets": {
            "browsers": ["> 1%", "ie >= 8"]
          },
          "useBuiltIns": true,
          "modules": 'commonjs'
        }],
        "stage-2",
        "stage-3"
      ]
    });

    ${transformedSource.code}`
```

**Comment by ccqgithub** [comment]
and this issue is the same reason: https://github.com/Kocal/jsdoc-vuejs/issues/13

**Comment by Kocal** [comment]
Well, the code I wrote for in https://github.com/Kocal/jsdoc-vuejs/issues/12#issuecomment-343772593 should also run Babel on `.js` file (see [sourceTransformer.js](https://github.com/Kocal/jsdoc-vuejs/blob/master/lib/sourceTransformer.js))..

Maybe there is somthing I'm missing, I will try to work on it in the evening

**Comment by ccqgithub** [comment]
@Kocal the js is already run by babel, but it is lost the presets, it is ok after i add the presets to it.

because the projects use diffirent of ES features,  the better way is let people pass custom babel options to `babal-register`

**Comment by Kocal** [comment]
Yeah that's seems pretty good, thanks, I will write a patch soon!
