### ISSUE TITLE
why you use 'vue-template-compuler' custom version ?

### ISSUE THREAD

**Issue by leeziiAtCn** [Kocal/jsdoc-vuejs#157]
if you use custom version , in my project , must use lastest version too.
for example : 
i use vue as " vue: '2.5.4'" ,you use compiler as  "vue-template-compiler:'^2.5.17'"

I will get an error, vue and vue-template-compiler version is not same,

can please u fix it ? or provide a optimize plan?

**Comment by leeziiAtCn** [comment]
u can use 
"peerDependencies": {
    "vue": "^2.5.2"
  },

**Comment by Kocal** [comment]
Fixed in v2.3.4
