### ISSUE TITLE
Feature request for vue-emit

### ISSUE THREAD

**Issue by pkuwwt** [Kocal/jsdoc-vuejs#160]
The events are important interfaces for vue component.

I tried `@event`, however, it generates a link to Test.html other than Test.vue.html.

Appreciated if this feature is included.

**Comment by Kocal** [comment]
See #102, feel free to contribute

**Comment by Kokosso** [comment]
@Kocal hello! I want to create this feature, but I have a question. Why do you ignore integration tests from ./cypress ?

**Comment by Kocal** [comment]
Hi @Kokosso, thanks for taking time for this. :+1: 

I don't understand your question, what do you mean by "ignore integration tests from ./cypress" ?

**Comment by Kokosso** [comment]
@Kocal  I'm sorry. I understood how your tests work and I have not any questions =)
