### ISSUE TITLE
Error with vuex mapGetters

### ISSUE THREAD

**Issue by siralb3rt** [Kocal/jsdoc-vuejs#19]
I'm having this error:

computed: _extends({}, (0, _vuex.mapGetters)({
                                   ^
TypeError: Cannot read property 'mapGetters' of undefined

This is from vuex mapGetters:
`
...mapGetters({
      getComponents: 'hd/getComponents'
    }),
`

**Comment by Kocal** [comment]
Did you use `import { mapGetters } from 'vuex'` ?

**Comment by siralb3rt** [comment]
I found the problem, I had "followImports": false.
with "followImports": true worked
