### ISSUE TITLE
Getting started example for newcomers

### ISSUE THREAD

**Issue by heitorlessa** [Kocal/jsdoc-vuejs#210]
Hello,

 Firstly, thank you so much for putting this together!

 I'm new to JSDoc so I might be doing something wrong as the generated docs don't have any sidebar menu items - Would you have any example for JSDoc newbies?

 Here's what I've done so far after trying to understand how to use this plugin and JSDoc:

**Installed JSdoc, this plugin and minami template**

``npm install jsdoc jsdoc-vuejs minami``

**Created a JSDoc configuration file - .jsdoc.json**

```json
{
    "tags": {
        "allowUnknownTags": true,
        "dictionaries": [
            "jsdoc"
        ]
    },
    "source": {
        "include": [
            "src/components",
            "src/views"
        ],
        "includePattern": "\\.(vue|js)$",
        "excludePattern": "(node_modules/|docs)"
    },
    "plugins": [
        "plugins/markdown",
        "node_modules/jsdoc-vuejs"
    ],
    "templates": {
        "cleverLinks": false,
        "monospaceLinks": true,
        "showInheritedInNav": true
    },
    "opts": {
        "destination": "./docs/",
        "encoding": "utf8",
        "private": true,
        "recurse": true,
        "template": "./node_modules/minami"
    }
}
```

**Added doc under scripts in package.json**

``"docs": "jsdoc -c .jsdoc.json"``

**Did a simple annotation in a SFC**

```javascript
export default {
  name: "FlightCard",
  props: {
    /**
     * @vue-prop {Object} details - Flight Class object
     */
    details: { type: Flight, required: true },
...
```

**Generated doc**

``npm run docs --verbose``

**Result**

All I see is a blank page with a Home link in the sidebar, and I can't see the FlightCard on the sidebar. By looking at the docs folder I can see these though when opening the HTML files directly they're pretty much code only:

```bash
tree docs                                        
docs
├── BookingFlight.vue.html
├── FlightToolbar.vue.html
├── fonts
│   ├── OpenSans-Bold-webfont.eot
│   ├── OpenSans-Bold-webfont.svg
│   ├── OpenSans-Bold-webfont.woff
│   ├── OpenSans-BoldItalic-webfont.eot
│   ├── OpenSans-BoldItalic-webfont.svg
│   ├── OpenSans-BoldItalic-webfont.woff
│   ├── OpenSans-Italic-webfont.eot
│   ├── OpenSans-Italic-webfont.svg
│   ├── OpenSans-Italic-webfont.woff
│   ├── OpenSans-Light-webfont.eot
│   ├── OpenSans-Light-webfont.svg
│   ├── OpenSans-Light-webfont.woff
│   ├── OpenSans-LightItalic-webfont.eot
│   ├── OpenSans-LightItalic-webfont.svg
│   ├── OpenSans-LightItalic-webfont.woff
│   ├── OpenSans-Regular-webfont.eot
│   ├── OpenSans-Regular-webfont.svg
│   ├── OpenSans-Regular-webfont.woff
│   ├── OpenSans-Semibold-webfont.eot
│   ├── OpenSans-Semibold-webfont.svg
│   ├── OpenSans-Semibold-webfont.ttf
│   ├── OpenSans-Semibold-webfont.woff
│   ├── OpenSans-SemiboldItalic-webfont.eot
│   ├── OpenSans-SemiboldItalic-webfont.svg
│   ├── OpenSans-SemiboldItalic-webfont.ttf
│   └── OpenSans-SemiboldItalic-webfont.woff
├── index.html
├── scripts
│   ├── linenumber.js
│   └── prettify
│       ├── Apache-License-2.0.txt
│       ├── lang-css.js
│       └── prettify.js
└── styles
    ├── jsdoc-default.css
    ├── prettify-jsdoc.css
    └── prettify-tomorrow.css
```

Any help is more than appreciated.

Thanks!

**Comment by nikolaydyankov** [comment]
I'm having the same issue. Works fine for the .js files, but doesn't generate anything for the SFCs.

**Comment by Kocal** [comment]
Hi,

Normally you have everything [here](https://github.com/Kocal/jsdoc-vuejs#usage).

And you can't use `@vue-prop` tag on the prop itself, you should put it before the `export default {}`.

Also you will find some example [here](https://github.com/Kocal/jsdoc-vuejs/tree/master/example) (for manami template and .vue documenting)

**Comment by heitorlessa** [comment]
Thanks Hugo - Been using JSDoc with esdoc extensively since the post here.
I will give this a try tomorrow and post results.

Thanks for taking the time to reply

**Comment by heitorlessa** [comment]
thanks a lot @Kocal that was it - It was indeed something as simple as moving the block of comments up.
