### ISSUE TITLE
JavaScript heap out of memory Error

### ISSUE THREAD

**Issue by lzm420241** [Kocal/jsdoc-vuejs#211]
#### JSDoc configuration
```js
{
  source: {
    include: [
      'test/packages/',
    ],
    includePattern: '\\.(vue|js)$',
  },
  opts: {
    encoding: 'utf8',
    recurse: true
  },
  recurseDepth: 2
}
```
#### my test/packages directory structure :
/dirA/index.js
/dirB/index.js     
/dirC/index.js   
/dirD/index.js  

the core code (index.js#31):
```js
 let componentName = e.doclet.meta.filename.replace(/\.(vue|js)$/, '');
```
i think the better code like this:
```js
let componentName = e.doclet.meta.filename.replace(/\.(vue|js)$/, '');
if(componentName === 'index'){
   if(config['includeIndexName'] && e.doclet.meta.path){
     componentName = e.doclet.meta.path.split('/').slice(-1)[0];
   } else {
     config['includeIndexName'] = true;
   }
}
```
i wish to handle the condition by config file, like this:
```js
{
  readFromPath: true,
  commonFileName: 'index'
}
```
```js
let componentName = '';
if(env.readFromPath && e.doclet.meta.filename.replace(/\.(vue|js)$/, '') === env.commonFileName) {
  componentName = e.doclet.meta.path.split('/').slice(-1)[0];
} else {
  componentName = e.doclet.meta.filename.replace(/\.(vue|js)$/, '');
}
```

**Comment by Kocal** [comment]
Hi,

I'm not sure to understand, can you provide a reproduction repository and reproduction steps?

What version of Node do you use?
What is your operating system?

**Comment by lzm420241** [comment]
@Kocal 
environment: 
node: 10.15.3
OS: macOS
description:
```bash
jsdoc -c config.js
```
i use vuejs to build my project, and i didn't modify vuejs source code.
let us the current condition:
we want to build n files, but the file name is index.js, then can you imagine that jsdoc will build how much file，just called module-index.html.
if the amount of index.js files is less than five, jsdoc will build successfully, but files is more than five, because of the module-index.html file is too bigger to cause heap out of memory.
so, we should consider how to solve the same name that we will build files，right？
usually，our project structure likes this:
projectA
   func1
   func2
   ...
   funcn
another structure:
projectA
  func1
     index.js
  func2
     index.js
  ...
  funcn
     index.js
