### ISSUE TITLE
[Feature] - Support for ...mapMutations as a method declaration

### ISSUE THREAD

**Issue by Elaniobro** [Kocal/jsdoc-vuejs#363]
I would like to be able to document in place a components mutations in the metods block above the `...mapMutations`
e.g.:
```js
    /**
     *@method resetIsAllExpanded
     * Sets boolean value in vuex store for isAllExpanded
     **/

    /**
     *@method setIsExpanded
     * Sets boolean value in vuex store for isExpanded
     **/
...mapMutations({
      resetIsAllExpanded: '_data/resetIsAllExpanded',
      setIsExpanded: '_data/setIsExpanded'
    }),
```

when doing so, it is throwing the documentation into the nav bar on the side, and not in scope with the rest of the documentation for said component. See below:

<img width="1044" alt="Screen Shot 2020-08-05 at 7 54 14 PM" src="https://user-images.githubusercontent.com/710847/89475203-9037f600-d755-11ea-9579-73f15d8b3bde.png">

**Comment by Kocal** [comment]
Hi,

I think you need to use `@memberof` with the name of your component, otherwise it won't be supported.

Can you try:
```js
/**
 * @memberof Card
 * @method resetIsAllExpanded Sets boolean value in vuex store for isAllExpanded
 */
```

**Comment by Elaniobro** [comment]
Hi @Kocal, yes, I did try your way. While it does supress it from showing up in the sidebar as noted in my previous comment, it does not, unfortunately appear within the card component methods. 

Any other ideas? And thank you for your reply!

**Comment by Kocal** [comment]
Hey, good news, I got it working by using `@memberof module:<Your component name>.methods`

See:
![Capture d’écran de 2020-08-16 22-46-02](https://user-images.githubusercontent.com/2103975/90343592-51862380-e012-11ea-90e1-55d20a831810.png)

by using the following code:
```js
    /**
     * @memberof module:Counter.methods
     * @method resetIsAllExpanded
     * @description Sets boolean value in vuex store for isAllExpanded
     */

    /**
     * @memberof module:Counter.methods
     * @method setIsExpanded
     * @description Sets boolean value in vuex store for isExpanded
     */
```

Tell me if it works for you!

**Comment by Elaniobro** [comment]
Huzzah! Thanks @Kocal this does in fact work!
