### ISSUE TITLE
Support vue 3

### ISSUE THREAD

**Issue by crutch12** [Kocal/jsdoc-vuejs#386]
To compile vue3 template we have to use [@vue/compiler-sfc](https://www.npmjs.com/package/@vue/compiler-sfc) because [vue-template-compiler](https://www.npmjs.com/package/vue-template-compiler) is for vue2 only.

**Comment by crutch12** [comment]
https://github.com/vuejs/vue-next/issues/670#issuecomment-579785869

> I think this is an issue that should be fixed in `vue-cli-plugin-vue-next` by not including `vue-template-compiler` (which is for 2.x only)

**Comment by InvenTorrey** [comment]
Is there any general timeline on support for vue3?

**Comment by DaveTorrey** [comment]
@Kocal @crutch12 I created a fork that uses the new @vue/compiler-sfc.  I put up an npm package until such time that an official one from Kocal might come up (also invited as maintainer on that package).

fork is available here:
https://github.com/DaveTorrey/jsdoc-vuejs

**Comment by Kocal** [comment]
Fixed by #440, released in [4.0.0](https://www.npmjs.com/package/jsdoc-vuejs/v/4.0.0), thanks @DaveTorrey!
