### ISSUE TITLE
Reference error variable is not defined for global variable

### ISSUE THREAD

**Issue by sagarkbhatt** [Kocal/jsdoc-vuejs#4]
while running JSDOC command I am getting above error for JS global variable that I am using in a component.

**Comment by Kocal** [comment]
The plugin actually execute the code between `<script>` tags. So yea, the plugin doesn't know about global variables.

What about testing if the variable exists before using it? You won't have any errors  I guess

**Comment by sagarkbhatt** [comment]
I am assigning global variable to vue component's data.
Any other solution like vue-template-loader works ??

**Comment by Kocal** [comment]
Mmmh, the only « solution » (not tested) I can provide for now is to test if the global variable exists :/

```js
/**
 * @vue
 */
export default {
  data() {
    return {
      bar: global.yourVariable ? yourVariable: null,
    }
  },
}
```

I'm not sure your component will still works, but at least it won't fail when running JSDoc

**Comment by Kocal** [comment]
@sagarkbhatt did it work?
