### ISSUE TITLE
exclude not working when followImports is true

### ISSUE THREAD

**Issue by siralb3rt** [Kocal/jsdoc-vuejs#41]
If I leave followImports: true and exclude node_modules from source it will follow imports in node_modules.

Is there any way I can ignore import paths ?

**Comment by Kocal** [comment]
It is not supported at the moment.

Feel free to contribute if you want this feature to be added! :slightly_smiling_face:

**Comment by Kocal** [comment]
Hey, I'm working on v2 and this problem won't happens anymore because it won't evaluate Vue components anymore (so `followImports` will disappear).

I'm closing.
