### ISSUE TITLE
vuejs-doc tooltips doesnt show in template area.

### ISSUE THREAD

**Issue by ivanushkaPr** [Kocal/jsdoc-vuejs#419]
Hello dear developers! I have a problem with you great tool.
If i use comments shown in documention. and afterthat moving mouse over imported component like this, i can see everything i documented. 

[
![useCase1](https://user-images.githubusercontent.com/26376786/117476463-ac2b2b00-af65-11eb-94b0-721de459aedf.png)
](url)

But, if i move my mouse over component in template area i see nothing. Is it my fault and i forget to add something to jsdoc conf.js file or your project doesnt have this functionality now?

![useCase2](https://user-images.githubusercontent.com/26376786/117476700-cfee7100-af65-11eb-9f54-efe4d9ffdafb.png)

**Comment by Kocal** [comment]
Hi, I think it's more an IDE issue than an issue from jsdoc or from jsdoc-vuejs.
Can you open a ticket to https://youtrack.jetbrains.com/issues/WEB please?

Thanks.
