### ISSUE TITLE
Generated docs contain url like this `%2520` and results in 404 error

### ISSUE THREAD

**Issue by sagarkbhatt** [Kocal/jsdoc-vuejs#5]

**Comment by Kocal** [comment]
Can you provide an example?

**Comment by sredbull** [comment]
change `doclet.alias = '(Vue) ' + componentName` to `doclet.alias = '(Vue)-' + componentName`
at /lib/vueTag.js

**Comment by Kocal** [comment]
Well, that will change the module name too: 
![capture d ecran de 2017-11-13 20-28-42](https://user-images.githubusercontent.com/2103975/32744891-521bddf6-c8b1-11e7-9c5b-e504162d7d9b.png)

Aaand... I don't find this very pretty..
I will search if it's possible to change the filename without changing the module name. I hope it exists, that would be awesome!

**Comment by ksbaozi** [comment]
umm..  i want to know why add blank space before componentName

**Comment by Kocal** [comment]
Well... idk, I wanted to add a badge-like to easily distinguish a Vue component and a plain-JS module.
But we can probably  use `doclet.alias = componentName + '.vue'` I think :)

**Comment by Kocal** [comment]
Check this PR #14
