### ISSUE TITLE
Source point to the wrong line of code

### ISSUE THREAD

**Issue by evanRoberto** [Kocal/jsdoc-vuejs#50]
https://kocal.github.io/jsdoc-vuejs-demo-docs/module-(Vue)%2520BetterCounter.html

**Comment by Kocal** [comment]
That's because I'm using vue-template-compiler to extract components `<script>` content.
And because of that, Vue components are seen like JavaScript only, it skip `<template>` content. 

I'm actually working on a v2 and I will try to do something about that.

**Comment by Kocal** [comment]
This seems to be fixed on v2 (#51), because we are not evaluating + executing Babel on `.vue` files anymore.

v2 is not already released (very soon), but I'm closing anyway.

**Comment by Kocal** [comment]
Re-opening because of #72.
It has not been fixed because the real problem is that every lines before `export default` is skipped.

I will write a patch ASAP.
